### ISSUE TITLE
Module compatibility

### ISSUE THREAD

**Issue by GabeMedrash** [krambuhl/custom-event-polyfill#3]
Would you accept a PR for bundling this for module usage? I'm thinking, particularly, plugging it into something like https://github.com/umdjs/umd/blob/master/returnExportsGlobal.js.

**Comment by krambuhl** [comment]
I think this module is appropriate as a auto-polyfill.  some people will want to use this API without having to rewrite code to use a custom module.  That said, https://www.npmjs.com/package/custom-event looks like does what you are asking already.  

I tend to prefer the commonjs/amd style, because the intent becomes more clear, but at the same time there is not a need for 2 modules that do the same thing.  Hope that helps.
